#!/bin/bash
dmd ./aofclient-voxlap-renderer/voxlap5.a ./aofclient-voxlap-renderer/*.d ./aofclient-voxlap-renderer/*.di -unittest -profile *.d *.di -gc -L-L/usr/local/lib -L-lslang -ofmain ./derelict/sdl2/*.d ./derelict/enet/*.d ./derelict/util/*.d
